import React, {PropTypes} from 'react';
import * as authorActions from '../../actions/authorActions';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import AuthorForm from './AuthorForm';
import NotFoundPage from '../NotFoundPage';
import toastr from 'toastr';

class ManageAuthorPage extends React.Component {
  constructor(props, context) {
    super(props, context);

    // Just using instance var here since it's not used in render.
    // Proof that this is cool. https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L42-L44
    this.formIsDirty = false;

    this.state = {
      author: Object.assign({}, this.props.author),
      errors: {},
      saveInProgress: false
    };

    this.setAuthorState = this.setAuthorState.bind(this);
    this.saveAuthor = this.saveAuthor.bind(this);
  }

	componentDidMount() {
		const route = this.props.route;
		const router = this.context.router;
		router.setRouteLeaveHook(route, this.routerWillLeave.bind(this));
	}

  routerWillLeave(nextLocation) {
    if (this.formIsDirty) {
      return 'Leave without saving?';
    }
  }

	setAuthorState(event) {
    this.formIsDirty = true;
		const field = event.target.name;
    const value = event.target.value;
    const author = this.state.author;
		author[field] = value;
		return this.setState({author: this.state.author});
	}

	formIsValid() {
		let formIsValid = true;
		let errors = {};

		if (this.state.author.firstName.length < 3) {
			errors.firstName = 'First name must be at least 3 characters.';
			formIsValid = false;
		}

		if (this.state.author.lastName.length < 3) {
			errors.lastName = 'Last name must be at least 3 characters.';
			formIsValid = false;
		}

		this.setState({errors: errors});
		return formIsValid;
	}

	saveAuthor(event) {
		event.preventDefault();

		if (!this.formIsValid()) {
			return;
		}

    this.formIsDirty = false;

    this.setState({saveInProgress: true});

    // This shows how to fire off code *after* the async action is complete
    // By waiting for the promise executed in the thunk to return.
    // We have to wait in this case because the ID is generated by the API.
    // Otherwise we'd see the course plop in *after* the redirect.
    // Initially, don't do this to show the behavior, then show how using
    // then fixes it and centralize redirectAndNotify.
    this.props.saveAuthor(this.state.author)
      .then( () => this.redirectAndNotify())
      .catch( error => alert(error) );
	}

  redirectAndNotify() {
    this.setState({saveInProgress: false});
    this.context.router.push('/authors');
    toastr.success('Author saved.');
  }

	render() {
    if (this.props.display404) return <NotFoundPage/>;
    if (this.props.loading && !this.state.saveInProgress) return null;

    return (
			<AuthorForm
				author={this.state.author}
				onChange={this.setAuthorState}
				onSave={this.saveAuthor}
				errors={this.state.errors}
        loading={this.props.loading}  />
		);
	}
}

ManageAuthorPage.propTypes = {
  // Data
  author: PropTypes.object,
  loading: PropTypes.bool.isRequired,
  display404: PropTypes.bool.isRequired,
  params: PropTypes.object.isRequired,
  route: PropTypes.object.isRequired,

  // Actions
  //actions: PropTypes.object.isRequired,
  //dispatch: PropTypes.object.isRequired,
  saveAuthor: PropTypes.func.isRequired
};

//Pull in the React Router context so router is available on this.context.router.
ManageAuthorPage.contextTypes = {
  router: React.PropTypes.object.isRequired
};

function getAuthorById(authors, id) {
  const author = authors.filter(author => author.id == id);
  if (author) return author[0]; //since filter returns an array, have to grab the first.
  return null;
}

function mapStateToProps(state, ownProps) {
  const authorId = ownProps.params.id; // from the path `/author/:id`
  let display404 = false;
  let author = { id: '', firstName: '', lastName: '' };

  if (authorId && state.authors.length > 0) {
    author = getAuthorById(state.authors, authorId);
    if (!author) display404 = true;
  }

  if (state.authors.length > 0 && authorId) {
    author = state.authors.filter(author => author.id == authorId)[0];
  }

  return {
    author,
    loading: state.ajaxCallsInProgress > 0,
    display404
  };
}

function mapDispatchToProps(dispatch) {
  // OPTION 1: Use dispatch directly in components.
  // Don't wrap action creators in dispatch.
  // Pass dispatch down to child components
  // But then you have to call dispatch in child components.
  // dispatch(authorActions.loadAuthors()).then( () => {

  // OPTION 2: Manually wrap action creators in dispatch calls
  // to show an alternative to bindActionCreators
  return {
    saveAuthor: author => dispatch(authorActions.saveAuthor(author))
  };

  // OPTION 3: bindActionCreators
  // return {
  //   actions: bindActionCreators(authorActions, dispatch)
  // };
}

export default connect(mapStateToProps, mapDispatchToProps)(ManageAuthorPage);
