export const LOADING = 'LOADING';

export const LOADED_AUTHORS = 'LOADED_AUTHORS';
export const CREATED_AUTHOR = 'CREATED_AUTHOR';
export const UPDATED_AUTHOR = 'UPDATED_AUTHOR';
export const DELETED_AUTHOR = 'DELETED_AUTHOR';

export const LOADED_COURSES = 'LOADED_COURSES';
export const CREATED_COURSE = 'CREATED_COURSE';
export const UPDATED_COURSE = 'UPDATED_COURSE';
export const DELETED_COURSE = 'DELETED_COURSE';
